format = "$os$container$shell$all"

[os]
format = '$symbol[$edition\($version\)]($style) '
style = "bold blue"
disabled = false

[shell]
format = '[\($indicator\)]($style) '
bash_indicator = 'bash'
powershell_indicator = 'pwsh'
tcsh_indicator = 'tcsh'
unknown_indicator = 'unknown shell'
style = 'bold green'
disabled = false

[time]
disabled = false
use_12hr = true
